# Jenkins Configuration as Code (JCasC)
# Montato su /var/jenkins_home/configuration-as-code.yaml
jenkins:
  systemMessage: "Jenkins CI/CD - Progetto cdci"
  securityRealm:
    local
  authorizationStrategy:
    loggedInUsersCanDoAnything
  pluginManagement:
    periodicUpdateInterval: 12
    installs:
      - name: git
        spec:
          version: "latest"
      - name: git-client
        spec:
          version: "latest"
      - name: workflow-aggregator
        spec:
          version: "latest"
      - name: workflow-cps
        spec:
          version: "latest"
      - name: workflow-basic-steps
        spec:
          version: "latest"
      - name: docker-plugin
        spec:
          version: "latest"
      - name: blueocean
        spec:
          version: "latest"
unsecured:
  allowedStackTraces: true
