# Jenkins Configuration as Code (JCasC)
# Montato su /var/jenkins_home/configuration-as-code.yaml
jenkins:
  systemMessage: "Jenkins CI/CD - Progetto cdci"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_UC_ADMIN_USER:-admin}"
          password: "${JENKINS_UC_ADMIN_PASSWORD}"
  authorizationStrategy:
    loggedInUsersCanDoAnything: { }